export default {
  login: "hookkl21",
  id: 16939218,
  node_id: "MDQ6VXNlcjE2OTM5MjE4",
  avatar_url: "https://avatars.githubusercontent.com/u/16939218?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/hookkl21",
  html_url: "https://github.com/hookkl21",
  followers_url: "https://api.github.com/users/hookkl21/followers",
  following_url: "https://api.github.com/users/hookkl21/following{/other_user}",
  gists_url: "https://api.github.com/users/hookkl21/gists{/gist_id}",
  starred_url: "https://api.github.com/users/hookkl21/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/hookkl21/subscriptions",
  organizations_url: "https://api.github.com/users/hookkl21/orgs",
  repos_url: "https://api.github.com/users/hookkl21/repos",
  events_url: "https://api.github.com/users/hookkl21/events{/privacy}",
  received_events_url: "https://api.github.com/users/hookkl21/received_events",
  type: "User",
  site_admin: false,
  name: "Masaki Hook",
  company: null,
  blog: "",
  location: "Orlando, FL",
  email: null,
  hireable: null,
  bio: "UCF graduate 2018 May, 3rd with Bachelor's  of Computer Science.\r\nLooking for entry level software engineering or data analyst.  ",
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2016-01-28T14:13:26Z",
  updated_at: "2022-05-13T10:19:08Z",
};
